name: Build MiPlots4

on:
  workflow_call:
    inputs:
      #
      # Common settings
      #
      app-name:
        description: |
          Application name in human-readable form.
          As it is supposed to be shown in messages
        type: string
        required: false
        default: ${{ github.repository }}

      app-name-slug:
        description: |
          Application name slug (part of release file name)
        type: string
        required: true

      #
      # Checkout settings
      #
      git-crypt-unlock:
        description: |
          Perform `git ctypt unlock` after each fresh repository checkout

          NOTE: don't forget to set the following secrets:
                  - GIT_CRYPT_GPG_KEY
                  - GIT_CRYPT_KEY_PASSWORD

        type: boolean
        required: false
        default: false

      checkout-submodules:
        description: |
          'Submodules' mode for 'actions/checkout' action
          '', 'false' - disable submodules support
          'true' - checkout submodules
          'recursive' - checkout submodules recursive
        type: string
        required: false
        default: ''

      #
      # Environment settings
      #
      env:
        description: |
          custom environment variables to set for all jobs in workflow
          as JSON-encoded map:
            { "MY_VAR_1": "awesome value",
              "VARIABLE_2": "not so awesome :)" }

          This input's envs are merged with secrets.env
          This input's envs have lower priority compared than secrets.env
        type: string
        required: false
        default: '{}'

      #
      # NodeJS settings
      #
      node-version:
        description: |
          Node version to use
        type: string
        required: true
      #
      # Cache control
      #
      cache-version:
        description: |
          Simple hack, that allows to 'reset' cache for particular job.

          Just change the value of this parameter and the next run will
          not find build cache and will have to start from scratch.

        type: string
        required: false
        default: 'v1'

      #
      # CDN control
      #
      cdn-url:
        description: |
          Main part of the CDN URL.
        type: string
        required: false
        default: 'https://cdn.mixcr.com'

      #
      # Build control
      #
      build-version:
        description: |
          Set version number in 'package.json' file to given value.
        type: string
        required: false
      build-script-name:
        description: |
          The name of a build script
        type: string
        required: true
        default: 'build'
      build-script-env:
        description: |
          JSON-encoded environment variables to set for 'npm run <build-script-name>':
          Example: '{ "SOME_VAR_NAME": "variable custom value" }'
        type: string
        required: false
        default: '{}'
      is-electron-application:
        description: |
          If 'true' enables cache for an Electron application,
          if 'false', enables cache for a generic NodeJS application.
        type: string
        required: false
        default: 'false'

      #
      # Build demo control
      #
      build-demo-version:
        description: |
          Set version number in 'package.json' file to given value.
        type: string
        required: false
      build-demo-script-name:
        description: |
          The name of a build script
        type: string
        required: true
        default: 'build-next'
      build-demo-artifact-path:
        description:
          The name of a distribution folder for demo suite.
        type: string
        required: false
        default: 'out'
      build-demo-artifact-retention:
        description: |
          Time in days to keep build artifacts before removing them
        type: number
        required: false
        default: 7
      #
      # AWS control for build demo
      #
      build-demo-s3-iam-role-to-assume:
        description: |
          The ARN of a IAM role to assume and configure the Actions environment with
          assumed role credentials.
        type: string
        required: false
        default: 'arn:aws:iam::511903394050:role/milab-euce1-prod-github-oidc-role-miplots4'
      build-demo-s3-region:
        description: |
          Upload build demo artifact's files to
          AWS S3 bucket in given region.
        type: string
        required: false
        default: 'eu-central-1'
      build-demo-s3-bucket:
        description: |
          Upload build demo artifact's files to
          given AWS S3 bucket.
        required: false
        type: string
        default: 'milab-euce1-prod-pkgs-s3-public-artifacts'
      build-demo-s3-path-prefix:
        description: |
          Prefix for all uploaded demo suite files.

          Demo suite will be uploaded to:
            's3://<bucket>/<path-prefix>/<repository>/<app-version>/<hash>/'

        required: false
        type: string
        default: 'cdn/internal/ci/tests'

      #
      # Test control
      #
      test-unit:
        description: |
          Run unit tests
        type: boolean
        required: false
        default: false
      test-unit-script-name:
        description: |
          The name of a unit test script
          e.g. 'test:e2e', 'test:main' e.t.c
        type: string
        required: false
        default: ''
      test-static:
        description: |
          Run static tests
        type: boolean
        required: false
        default: false
      test-static-script-name:
        description: |
          The name of a static test script
          e.g. 'lint', 'typecheck' e.t.c
        type: string
        required: false
        default: ''

      #
      # NPM registry settings
      #
      registry-url:
        description: |
          The npm registry url to set up for auth
          and publication of the node js package.
        type: string
        required: false
        default: 'https://npm.pkg.github.com'
      scope:
        description: |
          Scope for authenticating against npm registries.
        type: string
        required: false
        default: ${{ format('{0}{1}', '@', github.repository_owner) }}
      always-auth:
        description: |
          Set always-auth in npmrc.
        type: string
        required: false
        default: 'false'

      #
      # Notifications
      #
      notify-telegram:
        description: |
          Enable Telegram notifications
        required: false
        type: boolean
        default: true

      notify-build:
        description: |
          Enable notifications about build status (build ready/failed)
          Possible values are:
           - 'true' - send all notifications about build status (both success and failed)
           - 'failure-only' - send notification about failed builds, don't notify on success
           - 'success-only' - send notification about success builds, don't notify on failures
           - 'false' - don't send notifications about build results at all.
        required: false
        type: string
        default: 'true'

      notify-tests:
        description: |
          Enable notifications about tests status (ready/failed)
          Possible values are:
           - 'true' - send all notifications about tests status (both success and failed)
           - 'failure-only' - send notification about failed tests, don't notify on success
           - 'success-only' - send notification about success tests, don't notify on failures
           - 'false' - don't send notifications about tests results at all.
        required: false
        type: string
        default: 'true'

    secrets:
      env:
        description: |
          custom environment variables to set for all jobs in workflow
          as JSON-encoded map:
            { "MY_VAR_1": "awesome value",
              "VARIABLE_2": "not so awesome :)" }

          This input's envs are merged with inputs.env
          This input's envs have HIGHER priority compared than inputs.env
        required: false

      TELEGRAM_NOTIFICATION_TARGET:
        description: |
          ID of Telegram Channel or User to notify on build results.
        required: false

      TELEGRAM_API_TOKEN:
        description: |
          Telegram Bot API authorization token
        required: false

      GIT_CRYPT_GPG_KEY:
        description: |
          base64-encoded GPG key pair
          (see actions/git/crypt inputs description)
        required: false

      GIT_CRYPT_KEY_PASSWORD:
        description: |
          Password for GPG key
        required: false

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v4-beta

    outputs:
      is-release: ${{ steps.context.outputs.is-release }}

  build:
    name: :build
    runs-on: ubuntu-latest

    needs:
      - init

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v4-beta

      - uses: milaboratory/github-ci/actions/env@v4-beta
        with:
          inputs: ${{ inputs.env }}
          secrets: ${{ secrets.env }}

      - uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.checkout-submodules }}

      - uses: milaboratory/github-ci/actions/git/crypt@v4-beta
        if: inputs.git-crypt-unlock
        with:
          gpg-key: ${{ secrets.GIT_CRYPT_GPG_KEY }}
          gpg-key-password: ${{ secrets.GIT_CRYPT_KEY_PASSWORD }}

      - uses: milaboratory/github-ci/blocks/node/build/generic@v4-beta
        env: ${{ fromJSON(inputs.build-script-env) }}
        with:
          build-version: ${{ steps.context.outputs.current-version }}
          build-script-name: ${{ inputs.build-script-name }}
          node-version: ${{ inputs.node-version }}
          cache-version: ${{ inputs.cache-version }}
          is-electron-application: ${{ inputs.is-electron-application }}

  notify-build:
    name: Notify build
    runs-on: ubuntu-latest

    if: always()
      && inputs.notify-telegram
      && inputs.notify-build != 'false'
      && needs.build.result != 'cancelled'

    needs:
      - build

    steps:
      - uses: milaboratory/github-ci/blocks/notify/build@v4-beta
        with:
          telegram-target: ${{ secrets.TELEGRAM_NOTIFICATION_TARGET }}
          telegram-token: ${{ secrets.TELEGRAM_API_TOKEN }}

          build-status: |
            ${{ needs.build.result }}
          product-name: ${{ inputs.app-name }}

  build-demo-suite:
    name: :build-demo-suite
    runs-on: ubuntu-latest

    needs:
      - init
      - build

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v4-beta

      - uses: milaboratory/github-ci/actions/env@v4-beta
        with:
          inputs: ${{ inputs.env }}
          secrets: ${{ secrets.env }}

      - uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.checkout-submodules }}

      - uses: milaboratory/github-ci/actions/git/crypt@v4-beta
        if: inputs.git-crypt-unlock
        with:
          gpg-key: ${{ secrets.GIT_CRYPT_GPG_KEY }}
          gpg-key-password: ${{ secrets.GIT_CRYPT_KEY_PASSWORD }}

      - name: Set upload path for the next.js static build
        id: upload-path
        uses: milaboratory/github-ci/actions/shell@v4-beta
        env:
          VERSION: ${{ steps.context.outputs.current-version }}
          S3_PATH_PREFIX: ${{ inputs.build-demo-s3-path-prefix }}
          CDN_URL: ${{ inputs.cdn-url }}
        with:
          run: |
            _PATH_PREFIX=$(echo "${S3_PATH_PREFIX}" | cut -d '/' -f 2-)
            echo "${CDN_URL}/${_PATH_PREFIX}/${GITHUB_REPOSITORY}/${VERSION}/${GITHUB_SHA}/"

      - uses: milaboratory/github-ci/blocks/node/build/generic@v4-beta
        env:
          PATH_PREFIX: ${{ steps.upload-path.outputs.stdout }}
        with:
          build-version: ${{ steps.context.outputs.current-version }}
          build-script-name: ${{ inputs.build-demo-script-name }}
          node-version: ${{ inputs.node-version }}
          cache-version: ${{ inputs.cache-version }}
          is-electron-application: ${{ inputs.is-electron-application }}

      - id: artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('{0}-demo-suite', inputs.app-name-slug) }}
          path: ${{ inputs.build-demo-artifact-path }}
          retention-days: ${{ inputs.build-demo-artifact-retention }}

  upload-demo-suite:
    name: :upload-demo-suite
    runs-on: ubuntu-latest

    needs:
      - build-demo-suite
    permissions:
      id-token: write
      contents: read

    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context@v4-beta

      - uses: actions/download-artifact@v3
        with:
          name: ${{ format('{0}-demo-suite', inputs.app-name-slug) }}
          path: ${{ inputs.build-demo-artifact-path }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.build-demo-s3-iam-role-to-assume }}
          aws-region: ${{ inputs.build-demo-s3-region }}

      - name: Set upload path for the demo suite
        id: upload-path
        uses: milaboratory/github-ci/actions/shell@v4-beta
        env:
          VERSION: ${{ steps.context.outputs.current-version }}
        with:
          run: |
            echo "${GITHUB_REPOSITORY}/${VERSION}/${GITHUB_SHA}"

      - name: Upload demo suite
        uses: milaboratory/github-ci/actions/shell@v4-beta
        env:
          ARCHIVE_PATH: ${{ inputs.build-demo-artifact-path }}
          UPLOAD_PATH: ${{ steps.upload-path.outputs.stdout }}
          S3_BUCKET: ${{ inputs.build-demo-s3-bucket }}
          S3_PATH_PREFIX: ${{ inputs.build-demo-s3-path-prefix }}
        with:
          run: |
            aws s3 cp --recursive \
            "${ARCHIVE_PATH}" \
            "s3://${S3_BUCKET}/${S3_PATH_PREFIX}/${UPLOAD_PATH}"

    outputs:
      # Even constant outputs become initialized only after job start.
      # All outputs of skipped jobs are always empty.
      started: 'true'
      suite-url: https://cdn.mixcr.com/internal/ci/tests/${{ steps.upload-path.outputs.stdout }}/index.html

  notify-build-demo-suite:
    name: Notify build demo suite
    runs-on: ubuntu-latest

    if: always()
      && inputs.notify-telegram
      && inputs.notify-build != 'false'
      && needs.build-demo-suite.result != 'cancelled'
      && needs.upload-demo-suite.result != 'cancelled'

    needs:
      - build-demo-suite
      - upload-demo-suite

    steps:
      - id: search-tags
        uses: milaboratory/github-ci/actions/strings/json-list@v4-beta
        with:
          input: |
            build
            demosuite

      - uses: milaboratory/github-ci/blocks/notify/build@v4-beta
        with:
          telegram-target: ${{ secrets.TELEGRAM_NOTIFICATION_TARGET }}
          telegram-token: ${{ secrets.TELEGRAM_API_TOKEN }}

          build-status: |
            ${{ needs.build-demo-suite.result }}
          search-tags: ${{ steps.search-tags.outputs.result }}
          product-name: ${{ format('{0} - demo suite', inputs.app-name) }}
          additional-info: ${{ needs.upload-demo-suite.outputs.suite-url }}

  test-unit:
    name: :test (unit)
    runs-on: ubuntu-latest

    if: inputs.test-unit
    needs:
      - build
    permissions:
      contents: read
      packages: read

    steps:
      - uses: milaboratory/github-ci/actions/env@v4-beta
        with:
          inputs: ${{ inputs.env }}
          secrets: ${{ secrets.env }}

      - uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.checkout-submodules }}

      - uses: milaboratory/github-ci/actions/git/crypt@v4-beta
        if: inputs.git-crypt-unlock
        with:
          gpg-key: ${{ secrets.GIT_CRYPT_GPG_KEY }}
          gpg-key-password: ${{ secrets.GIT_CRYPT_KEY_PASSWORD }}

      - id: test
        uses: milaboratory/github-ci/blocks/node/test@v4-beta
        with:
          test-name: ${{ inputs.test-unit-script-name }}
          node-version: ${{ inputs.node-version }}
          cache-version: ${{ inputs.cache-version }}
          is-electron-application: ${{ inputs.is-electron-application }}
          registry-url: ${{ inputs.registry-url }}
          scope: ${{ inputs.scope }}
          always-auth: ${{ inputs.always-auth }}
          npm-auth-token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      # Even constant outputs become initialized only after job start.
      # All outputs of skipped jobs are always empty.
      started: 'true'

  notify-test-unit:
    name: notify unit test
    runs-on: ubuntu-latest

    if: always()
      && needs.test-unit.outputs.started == 'true'
      && inputs.notify-tests != 'false'

    needs:
      - test-unit

    steps:
      - uses: milaboratory/github-ci/blocks/notify/tests@v4-beta
        with:
          telegram-target: ${{ secrets.TELEGRAM_NOTIFICATION_TARGET }}
          telegram-token: ${{ secrets.TELEGRAM_API_TOKEN }}

          notification-mode: ${{ inputs.notify-tests }}
          tests-status: ${{ needs.test-unit.result }}
          tests-type: 'Unit'

          product-name: ${{ inputs.app-name }}

  test-static:
    name: :test (static)
    runs-on: ubuntu-latest

    if: inputs.test-static
    needs:
      - build
    permissions:
      contents: read
      packages: read

    steps:
      - uses: milaboratory/github-ci/actions/env@v4-beta
        with:
          inputs: ${{ inputs.env }}
          secrets: ${{ secrets.env }}

      - uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.checkout-submodules }}

      - uses: milaboratory/github-ci/actions/git/crypt@v4-beta
        if: inputs.git-crypt-unlock
        with:
          gpg-key: ${{ secrets.GIT_CRYPT_GPG_KEY }}
          gpg-key-password: ${{ secrets.GIT_CRYPT_KEY_PASSWORD }}

      - id: test
        uses: milaboratory/github-ci/blocks/node/test@v4-beta
        with:
          test-name: ${{ inputs.test-static-script-name }}
          node-version: ${{ inputs.node-version }}
          cache-version: ${{ inputs.cache-version }}
          is-electron-application: ${{ inputs.is-electron-application }}
          registry-url: ${{ inputs.registry-url }}
          scope: ${{ inputs.scope }}
          always-auth: ${{ inputs.always-auth }}
          npm-auth-token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      # Even constant outputs become initialized only after job start.
      # All outputs of skipped jobs are always empty.
      started: 'true'

  notify-test-static:
    name: notify static test
    runs-on: ubuntu-latest

    if: always()
      && needs.test-static.outputs.started == 'true'
      && inputs.notify-tests != 'false'

    needs:
      - test-static

    steps:
      - uses: milaboratory/github-ci/blocks/notify/tests@v4-beta
        with:
          telegram-target: ${{ secrets.TELEGRAM_NOTIFICATION_TARGET }}
          telegram-token: ${{ secrets.TELEGRAM_API_TOKEN }}

          notification-mode: ${{ inputs.notify-tests }}
          tests-status: ${{ needs.test-static.result }}
          tests-type: 'Static'

          product-name: ${{ inputs.app-name }}